name: "speech-to-text"
max_batch_size: 1
backend: "python"

input [
	{
		name: "raw_audio"
		data_type: TYPE_STRING
		dims: [ -1 ]
	}
]

output {
    name: "GENERATED_OUTPUT"
    data_type: TYPE_STRING
    dims: [ -1 ]
}

version_policy: {specific: {versions: [1]}}
# temporary disabled dynamic batching because of model request parameterization

instance_group [
    {
      count: 1
      kind: KIND_GPU
	  gpus: [ 0 ]
	  rate_limiter {
	      resources [
		    {
			  name: "R1"
		    }
		  ]
	  }
    }
]

