name: "face-analysis"
max_batch_size: 0
backend: "python"

input [
	{
		name: "video_url"
		data_type: TYPE_STRING
		dims: [ -1 ]
	}
]

output {
    name: "EMBEDDINGS"
    data_type: TYPE_FP32
    dims: [ -1, 512 ]
}

instance_group [{ kind: KIND_CPU }]

