name: "speech-to-text-rus"
max_batch_size: 0
backend: "python"

input [
	{
		name: "audio_path"
		data_type: TYPE_STRING
		dims: [ -1 ]
	}
]

output {
    name: "GENERATED_OUTPUT"
    data_type: TYPE_STRING
    dims: [ -1 ]
}

instance_group [
    {
      count: 1
      kind: KIND_GPU
	  gpus: [ 0 ]
	  rate_limiter {
	      resources [
		    {
			  name: "R0"
		    }
		  ]
	  }
    }
]

