name: "xclip-video-handler"
max_batch_size: 0
backend: "python"

input [
	{
		name: "video_url"
		data_type: TYPE_STRING
		dims: [ -1 ]
	}
]

output [
	{
		name: "EMBEDDING"
		data_type: TYPE_FP32
		dims: [ 1024 ]
	}
]

instance_group [{ kind: KIND_CPU }]

